### ISSUE TITLE
Tutorial please

### ISSUE THREAD

**Issue by Adzido** [if-ai/IF_prompt_MKR#1]
How to install it? 
What this mean?
CMD_FLAGS --model-menu --model Wizard-Vicuna-13B-Uncensored-GPTQ --model_type llama --wbits 4 --groupsize 128 --chat --no-stream api --listen-port 7861 --listen

I have to add this somewhere in some file or? --api i know, it have to in webui-user.bat but smth else?

**Comment by if-ai** [comment]
I made a tutorial already is in the readme, In the tutorial I mention you need a software called Oobabooga which is similar to A1111 but for running LLMS like chatgpt in your computer. 
The bit you mentioned step is not necessary since you can update the parameters inside your settings in Oobabooga but I put here because is more convenient if you want you can edit the webui.py like that using your own flags like you do in Automatic1111 with webui-user.bat  like this  https://i.imgur.com/HVIcq6U.png

**Comment by BasedAnon** [comment]
You need to post clearer instructions, how do we do this:  _"Move the characters from the extension folder to your oobabooga Character Folder and place the script on extensions or install it from url inside A1111"_
Do you mean "move the contents of the characters folder from the extension's folder to Oobabooga's Characters folder?"
And what does "place the script on extensions" mean?  How do we install scripts from url?  Do you mean what's in the scripts folder?
Being extremely precise is important, otherwise people can't use your extension.

**Comment by if-ai** [comment]
okay, Yes is true, I am sorry that people are having a hard time, I will make a new tutorial. Meanwhile you need to move the characters from the characters extension folder into the oobabooga characters folder then the extension. the instruction to place the IF_prompt_MKR  folder into the SD A1111 extension folder is not needed anymore because you can just download from the automatic1111 extension list and that takes care of that
  
![explorer_FdHrILWjvH](https://github.com/if-ai/IF_prompt_MKR/assets/21185218/0cd57bb6-6f02-4ecb-a40a-37aaa515fed5)

**Comment by LightTemplar** [comment]
Do I need also to copy `presets`? There were an error by `oobabooga`, that file `presets/IF_promptMKR_preset.yaml` wasn't found, so I copied it too.

**Comment by if-ai** [comment]
Yes from the minute 3:18 of my last SDXL+IF Prompt MKR video I explained
how to do it  https://youtu.be/Bg9jV2Vxkk4
